algoritmo "Média"
// Função :
// Autor :
// Data : 26/08/2014
// Seção de Declarações 
var
n1, n2, n3, n4, m : real

inicio
// Seção de Comandos

escreval ("Algorítimo para obtenção de média")
escreval ("Insira a nota #1")
leia (n1)
escreval ("Insira a nota #2")
leia (n2)
escreval ("Insira a nota #3")
leia (n3)
escreval ("Insira a nota #4")
leia (n4)

m <- (n1+n2+n3+n4)/4

escreval ("A média do aluno é ",m)
fimalgoritmo
